### ISSUE TITLE
Callback 

### ISSUE THREAD

**Issue by wadsonlucas** [gerencianet/gn-api-whmcs-pix#1]
Seria ideal também adicionar atualização do QR CODE, fatura alterada depois que é gerada o valor não atualiza. Refresh após recebimento do callback tbm!

**Comment by jvoliveiraGN** [comment]
Oi @wadsonlucas tudo bem? 😄 
Muito obrigado pelo feedback! Vou levar essa demanda para análise!
Quanto a atualização automática dos pedidos via callback, vou verificar se está ocorrendo alguma incompatibilidade, pois deveria estar funcionando normalmente.
Em breve te dou um retorno! 😃
