### ISSUE TITLE
Incompatibilidade com GN WHMCS

### ISSUE THREAD

**Issue by rbaldasso** [gerencianet/gn-api-whmcs-pix#2]
Quando o modulo WHMCS da Gerencianet também está instalado no WHMCS não é possivel acessar a config de gateways do whmcs

Fatal error: Cannot redeclare delete() (previously declared in /home/<user>/painel/modules/gateways/gerencianet_lib/BD_access.php:44) in /home/<user>/painel/modules/gateways/gerencianetpix/gerencianetpix_lib/database_interaction.php on line 167

**Comment by jvoliveiraGN** [comment]
Oi @rbaldasso tudo bem? 😄 
Essa incompatibilidade já está sendo corrigida por nossa equipe!
Estamos realizando alguns testes e em breve disponibilizaremos a atualização de correção!
Te dou um retorno aqui mesmo na issue, ta bom? 🙂

**Comment by jvoliveiraGN** [comment]
Oi @rbaldasso tudo bem?
Incompatibilidade corrigida na [nova release](https://github.com/gerencianet/gn-api-whmcs/releases/tag/1.0.0)!
Basta atualizar os arquivos do módulo WHMCS para boletos!
Quaisquer dúvidas, estamos à disposição!
