### ISSUE TITLE
Código QR inválido se a invoice está vencida

### ISSUE THREAD

**Issue by rbaldasso** [gerencianet/gn-api-whmcs-pix#5]
Caso o customer tente pagar uma invoice vencida (due date no passado) o código QR gerado é invalido, inclusive o copia e cola. É necessário criar uma nova invoice com a data atualizada pois aparentemente é feito um cache da transação no sistema da gerencianet, e não é possível atualizar o QR code já gerado.

**Comment by rbaldasso** [comment]
Solução 1 seria verificar se a due date está no passado e caso sim, atualizar para o dia especificado na config do módulo. E a solução 2 seria implementar o botao de atualizar o código QR conforme issue #1 para possibilitar atualizar do qr após geração.

**Comment by jvoliveiraGN** [comment]
Oi @rbaldasso tudo bem? 😄 
Infelizmente, no momento, não será possível prosseguir com essa funcionalidade.
Uma sugestão que acredito que possa contornar essa situação, é definir a **Validade da Cobrança** em um número maior de dias, evitando assim a necessidade de atualizar a cobrança.
https://gnetbr.com/BkgwFsiNwO

**Comment by rbaldasso** [comment]
O problema são usuários que geram cobranças vencidas, ex serviço suspenso, que o cliente nunca acessou a fatura antes, logo, não há codigo qr ja gerado.

Já fiz as devidas alterações no código em nosso ambiente e está funcionando. Caso a fatura esteja suspensa o gateway pega current date e aplica a validade da cobrança definida lá, antes de fazer a transação e enviar para a gerencianet.
