### ISSUE TITLE
Exception: Authorization Error 400: Bad Request

### ISSUE THREAD

**Issue by wickhost** [gerencianet/gn-api-whmcs-pix#8]
Olá, eu configurei tudo corretamente, porem essa mensagem ocorre na hora de salvar as configurações porem elas salvam e gera o pix corretamente, esse erro ocorre ao salvar as configurações do módulo mas não gera nem um log de erro.

![Screenshot_1](https://user-images.githubusercontent.com/51794949/117576107-efe37900-b0ba-11eb-8582-2239d18c4143.jpg)

**Comment by jvoliveiraGN** [comment]
Oi @wickhost tudo bem? 😄
Por favor, ative o modo debug nas configurações do módulo e envie um print para que possamos avaliar o log.
Se puder passar mais detalhes em nossa comunidade do Discord (https://discord.gg/bHKhsj9WCj) para que possamos verificar no privado as configurações do seu módulo!
Quaisquer dúvidas, estamos à disposição!
