### ISSUE TITLE
WHMCS 8.1.3 x PHP 7.3

### ISSUE THREAD

**Issue by luizcpj** [gerencianet/gn-api-whmcs-pix#9]
Estou obtendo o erro logo ao ativar o módulo:

Error: Call to undefined method Gerencianet\Gerencianet::getInstance() in /home/cliencl/public_html/central/modules/gateways/gerencianetpix/gerencianetpix_lib/api_interaction.php:30
Stack trace:
#0 /home/cliencl/public_html/central/includes/hooks/gerencianetpix.php(104): getGerencianetApiInstance(Array)
#1 /home/cliencl/public_html/central/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): WHMCS\Utility\SafeInclude::{closure}(Array)
#2 /home/cliencl/public_html/central/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run('AdminAreaPage', Array, false)
#3 /home/cliencl/public_html/central/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic('run', Array)
#4 /home/cliencl/public_html/central/vendor/whmcs/whmcs-foundation/lib/Admin.php(0): run_hook('AdminAreaPage', Array)
#5 /home/cliencl/public_html/central/vendor/whmcs/whmcs-foundation/lib/Admin.php(0): WHMCS\Admin->output()
#6 /home/cliencl/public_html/central/if-admin/configgateways.php(0): WHMCS\Admin->display()
#7 {main}

**Comment by jvoliveiraGN** [comment]
Oi @luizcpj  tudo bem? 😄
Você possui o módulo da Gerencianet para WHMCS Boletos? Pode estar ocorrendo incompatibilidade de versões.
Por favor, nos informe mais detalhes em nossa comunidade do Discord (https://discord.gg/bHKhsj9WCj) para que possamos verificar no privado as configurações do seu módulo!
Quaisquer dúvidas, estamos à disposição!
